### ISSUE TITLE
后端运行一段时间后掉线

### ISSUE THREAD

**Issue by thomas0612** [glzjin/shadowsocks#10]
日志如图
![image](https://cloud.githubusercontent.com/assets/7479313/19954753/1222e492-a1b6-11e6-9a48-90f3cd999af8.png)

2016-11-02 06:19:37 INFO     db_transfer.py:494 db start server at port [10301] pass [123456] protocol [auth_sha1_v2_compatible] obfs [tls1.2_ticket_auth_compatible]
2016-11-02 06:19:37 INFO     server_pool.py:138 starting server at [::]:10301
2016-11-02 06:19:37 INFO     server_pool.py:164 starting server at 0.0.0.0:10301
2016-11-02 06:19:37 INFO     db_transfer.py:494 db start server at port [41470] pass [96Vt3j] protocol [origin] obfs [plain]
2016-11-02 06:19:37 INFO     server_pool.py:138 starting server at [::]:41470
2016-11-02 06:19:37 INFO     server_pool.py:164 starting server at 0.0.0.0:41470
2016-11-02 06:19:37 INFO     db_transfer.py:494 db start server at port [63166] pass [5weqjP] protocol [origin] obfs [plain]
2016-11-02 06:19:37 INFO     server_pool.py:138 starting server at [::]:63166
2016-11-02 06:19:37 INFO     server_pool.py:164 starting server at 0.0.0.0:63166
2016-11-02 06:20:17 INFO     auto_block.py:59 Read hosts.deny from line 5659
2016-11-02 06:20:39 ERROR    db_transfer.py:537 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 529, in thread_db
    db_instance.push_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 210, in push_db_all_user
    update_transfer = self.update_all_user(dt_transfer)
  File "/root/shadowsocks/db_transfer.py", line 100, in update_all_user
    cur.execute("INSERT INTO `ss_node_info` (`id`, `node_id`, `uptime`, `load`, `log_time`) VALUES (NULL, '" + str(get_config().NODE_ID) + "', '" + str(self.uptime()) + "', '" + str(self.load()) + "', unix_timestamp()); ")
  File "/root/shadowsocks/db_transfer.py", line 176, in load
    return os.popen("cat /proc/loadavg | awk '{ print $1\" \"$2\" \"$3 }'").readlines()[0]
OSError: [Errno 12] Cannot allocate memory

2016-11-02 06:21:19 INFO     auto_block.py:59 Read hosts.deny from line 5661
2016-11-02 06:21:39 ERROR    tcprelay.py:966 [Errno 104] Connection reset by peer
2016-11-02 06:21:39 ERROR    tcprelay.py:967 exception from ::ffff:114.111.167.24:23058
2016-11-02 06:21:40 ERROR    db_transfer.py:537 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 529, in thread_db
    db_instance.push_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 210, in push_db_all_user
    update_transfer = self.update_all_user(dt_transfer)
  File "/root/shadowsocks/db_transfer.py", line 100, in update_all_user
    cur.execute("INSERT INTO `ss_node_info` (`id`, `node_id`, `uptime`, `load`, `log_time`) VALUES (NULL, '" + str(get_config().NODE_ID) + "', '" + str(self.uptime()) + "', '" + str(self.load()) + "', unix_timestamp()); ")
  File "/root/shadowsocks/db_transfer.py", line 176, in load
    return os.popen("cat /proc/loadavg | awk '{ print $1\" \"$2\" \"$3 }'").readlines()[0]
OSError: [Errno 12] Cannot allocate memory

2016-11-02 06:22:21 INFO     auto_block.py:59 Read hosts.deny from line 5663
2016-11-02 06:22:42 ERROR    db_transfer.py:537 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 529, in thread_db
    db_instance.push_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 210, in push_db_all_user
    update_transfer = self.update_all_user(dt_transfer)
  File "/root/shadowsocks/db_transfer.py", line 100, in update_all_user
    cur.execute("INSERT INTO `ss_node_info` (`id`, `node_id`, `uptime`, `load`, `log_time`) VALUES (NULL, '" + str(get_config().NODE_ID) + "', '" + str(self.uptime()) + "', '" + str(self.load()) + "', unix_timestamp()); ")
  File "/root/shadowsocks/db_transfer.py", line 176, in load
    return os.popen("cat /proc/loadavg | awk '{ print $1\" \"$2\" \"$3 }'").readlines()[0]
OSError: [Errno 12] Cannot allocate memory

2016-11-02 06:23:22 INFO     auto_block.py:59 Read hosts.deny from line 5665
2016-11-02 06:23:23 INFO     auto_block.py:133 Remote Block ip:60.186.31.124
2016-11-02 06:23:43 ERROR    db_transfer.py:537 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 529, in thread_db
    db_instance.push_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 210, in push_db_all_user
    update_transfer = self.update_all_user(dt_transfer)

**Comment by glzjin** [comment]
按照安装说明优化过了吗？
