### ISSUE TITLE
创建新的节点时，shadowsocks后端报错。userapiconfig.py是在新旧节点上是一模一样的。

### ISSUE THREAD

**Issue by terryops** [glzjin/shadowsocks#2]
错误通过supervisorctl tail -f shadowsocks stderr查看
>`db_transfer.py:557 Traceback (most recent call last):
File "/root/shadowsocks/db_transfer.py", line 550, in thread_db
rows = db_instance.pull_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 256, in pull_db_all_user
    cur.execute("SELECT " + ','.join(keys) + " FROM user WHERE `class`>="+ str(nodeinfo[1]) +" "+node_group_sql+" AND`enable`=1 AND `expire_in`>now() AND `transfer_enable`>`u`+`d`")
  File "/usr/lib/python2.6/site-packages/cymysql/cursors.py", line 133, in execute
    self.errorhandler(exc, value)
  File "/usr/lib/python2.6/site-packages/cymysql/cursors.py", line 35, in errorhandler
    self.connection.errorhandler(self, errorclass, errorvalue)
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 118, in errorhandler
    raise errorvalue
InternalError: (1054, u"Unknown column 'is_multi_user' in 'field list'")`

**Comment by glzjin** [comment]
@terryops 请升级你的前端版本，确保你已经导入了 glzjin_27.sql 这个文件

**Comment by terryops** [comment]
SQL 查询：

>`ALTER TABLE `user` ADD `is_multi_user` INT NOT NULL DEFAULT '0' AFTER `is_hide``
MySQL 返回： 文档
>`#1054 - Unknown column 'is_hide' in 'user' `

**Comment by glzjin** [comment]
@terryops 请仔细按照升级日志里的说明逐版本升级。

**Comment by terryops** [comment]
直接用all.sql行不行？

**Comment by kaikaisd** [comment]
@terryops 先導入glzjin_25.sql再導入27的,即可
